name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  CMDSTAN_VERSION: "2.31.0" 

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install cmdstanpy
        run: |
          python -m pip install --upgrade pip wheel
          pip install "cmdstanpy==1.0.4"
      - name: CmdStan installation cacheing
        uses: actions/cache@v2
        with:
          path: ~/.cmdstan
          key: ${{ runner.os }}-cmdstan-${{ env.CMDSTAN_VERSION }}

      - name: Install CmdStan (Linux, macOS)
        if: matrix.os != 'windows-latest'
        run: |
          python -m cmdstanpy.install_cmdstan --version "${{ env.CMDSTAN_VERSION }}" --cores 2
      - name: Install dependencies
        run: |
          sudo apt install pandoc
          pip install -r docs/requirements-docs.txt
      - name: Sphinx build
        run: |
          cd docs
          make html
          cd ..
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
          force_orphan: true